drupal-ukraine/dcamp-site

- .docksal/commands/dump
> DCK-Docksal: Add new command dump

- .docksal/docksal.env
- README.md
> **Updated README file. Add description and explanation for contributors. Also added instruction how to up project in local env and start to contribute**
> DCK-XXX: Update README file

- .docksal/commands/init
- .docksal/commands/rebuild
- config/sync/editor.editor.basic_html.yml
- config/sync/filter.format.basic_html.yml
- config/sync/user.role.anonymous.yml
- config/sync/user.role.authenticated.yml
- docroot/themes/custom/dckyiv/style/scss/abstractions/_container.scss
- docroot/themes/custom/dckyiv/style/scss/base/_drupal.scss
- docroot/themes/custom/dckyiv/style/scss/base/_layout.scss
- docroot/themes/custom/dckyiv/style/scss/components/_paragraph--html-widget.scss
- docroot/themes/custom/dckyiv/style/scss/variables/_colors.scss
- docroot/themes/custom/dckyiv/style/scss/wysiwyg.scss
> DCK-11: Add Typography style and style for HTML Widget

- .docksal/commands/init
- .docksal/commands/rebuild
- docroot/themes/custom/dckyiv/style/scss/components/_paragraph--html-widget.scss
> DCK-12: Update spaces between elements in html widget

- docroot/themes/custom/dckyiv/dckyiv.libraries.yml
> DCK-16: Fix for js file

- docroot/modules/custom/dckyiv_core/js/countdown-widget.js
> Fixed translation

- .github/ISSUE_TEMPLATE/bug_report.md
> DCK-20: : Fix issue template

- docroot/themes/custom/dckyiv/js/global-menu.js
> **Allow click to link in the main menu without next level**
> DCK-21: Fix menu click in main menu

- docroot/modules/custom/dckyiv_core/dckyiv_core.module
> Fix bug with translation and moderation

- docroot/themes/custom/dckyiv/style/scss/base/_drupal.scss
- docroot/themes/custom/dckyiv/style/scss/base/_layout.scss
- docroot/themes/custom/dckyiv/style/scss/components/_commerce-cart-form.scss
- docroot/themes/custom/dckyiv/style/scss/components/_commerce-checkout-form.scss
- docroot/themes/custom/dckyiv/style/scss/components/_commerce-product-full.scss
- docroot/themes/custom/dckyiv/style/scss/components/_list-as-dropdown.scss
- docroot/themes/custom/dckyiv/style/scss/components/_my-presentations.scss
- docroot/themes/custom/dckyiv/style/scss/components/_node-presentation-form.scss
> **Add container for all pages and add style for table**
> DCK-23: Fix positions and table

- config/sync/views.view.commerce_orders.yml
- docroot/modules/custom/dckyiv_user/src/Form/DCKUserLoginForm.php
> DCK-66 Fixed back redirect for user after login action.

- docroot/themes/custom/dckyiv/style/scss/abstractions/_container.scss
- docroot/themes/custom/dckyiv/style/scss/base/_drupal.scss
- docroot/themes/custom/dckyiv/style/scss/base/_layout.scss
- docroot/themes/custom/dckyiv/style/scss/components/_commerce-cart-form.scss
- docroot/themes/custom/dckyiv/style/scss/components/_footer.scss
- docroot/themes/custom/dckyiv/style/scss/components/_list-as-dropdown.scss
- docroot/themes/custom/dckyiv/style/scss/components/_mobilenav.scss
- docroot/themes/custom/dckyiv/style/scss/components/_my-presentations.scss
- docroot/themes/custom/dckyiv/style/scss/components/_paragraph--camp-products.scss
- docroot/themes/custom/dckyiv/style/scss/components/_paragraph--view-mode--in-wrapper.scss
- docroot/themes/custom/dckyiv/style/scss/components/_paragraph--wrapper-webform.scss
- docroot/themes/custom/dckyiv/style/scss/components/_user_login_form.scss
- docroot/themes/custom/dckyiv/templates/navigation/links--dropbutton--operations.html.twig
> DCK-21: Small fixes for style

- docroot/modules/custom/dckyiv_core/dckyiv_core.module
> DCK-27: Override revision form in presentation form

- config/sync/content_moderation_notifications.content_moderation_notification.approved_candidate.yml
- config/sync/content_moderation_notifications.content_moderation_notification.need_changes.yml
- config/sync/content_moderation_notifications.content_moderation_notification.presentation_has_been_added.yml
- config/sync/content_moderation_notifications.content_moderation_notification.send_my_topic_to_review_author.yml
- config/sync/workflows.workflow.presentation.yml
> **Added Approved Candidate workflow state and updated notifiations content**
> Notifications update

- docroot/modules/custom/dckyiv_core/dckyiv_core.module
> Hided Preview button

- config/sync/core.entity_form_display.node.presentation.default.yml
- config/sync/core.entity_view_display.node.presentation.default.yml
- config/sync/field.field.node.presentation.field_image.yml
- config/sync/image.style.public_speaker_images.yml
- config/sync/views.view.presentation_list.yml
- docroot/themes/custom/dckyiv/style/scss/components/_paragraph--type--presentations.scss
> DCK-33: Update Presentation list in front page

- config/sync/views.view.presentation_list.yml
- docroot/themes/custom/dckyiv/style/scss/components/_paragraph--type--presentations.scss
> DCK-34: Hide bg image

- config/sync/core.entity_form_display.paragraph.presentations.default.yml
- config/sync/core.entity_form_display.paragraph.sponsor_wrapper.default.yml
- config/sync/core.entity_view_display.paragraph.presentations.default.yml
- config/sync/core.entity_view_display.paragraph.sponsor_wrapper.default.yml
- config/sync/field.field.paragraph.presentations.field_title.yml
- config/sync/field.field.paragraph.sponsor_wrapper.field_title.yml
- docroot/themes/custom/dckyiv/style/scss/base/_drupal.scss
- docroot/themes/custom/dckyiv/style/scss/components/_paragraph--camp-products.scss
- docroot/themes/custom/dckyiv/style/scss/components/_paragraph--html-widget.scss
- docroot/themes/custom/dckyiv/style/scss/components/_paragraph--sponsors.scss
- docroot/themes/custom/dckyiv/style/scss/components/_paragraph--type--presentations.scss
- docroot/themes/custom/dckyiv/style/scss/components/_paragraph--view-mode--in-wrapper.scss
- docroot/themes/custom/dckyiv/style/scss/components/_paragraph--wrapper-teasers.scss
- docroot/themes/custom/dckyiv/templates/paragraph/paragraph--presentations.html.twig
- docroot/themes/custom/dckyiv/templates/paragraph/paragraph.html.twig
> DCK-35: Add titles for few paragraphs

- docroot/themes/custom/dckyiv/style/scss/components/_paragraph--sponsors.scss
- docroot/themes/custom/dckyiv/templates/content/taxonomy-term--sponsor-type.html.twig
> DCK-36: Update logic for sponsor wrapper style

- config/sync/core.entity_form_display.paragraph.sponsor_wrapper_full.default.yml
- config/sync/core.entity_view_display.paragraph.sponsor_wrapper_full.default.yml
- config/sync/field.field.paragraph.sponsor_wrapper_full.field_sponsor_section.yml
- config/sync/field.field.paragraph.sponsor_wrapper_full.field_title.yml
- config/sync/paragraphs.paragraphs_type.sponsor_wrapper_full.yml
- docroot/themes/custom/dckyiv/style/scss/base/_drupal.scss
- docroot/themes/custom/dckyiv/style/scss/components/_paragraph--sponsors.scss
> Create new paragraph like Sponsor Wrapper but with full width. You can add to the londing page.
> DCK-37: Add new Sponsor Wrap Full Width brick

- .docksal/commands/init
- .docksal/commands/rebuild
- config/sync/core.entity_form_display.node.sponsor.default.yml
- config/sync/core.entity_view_display.node.sponsor.default.yml
- config/sync/core.entity_view_display.node.sponsor.only_image.yml
- config/sync/core.entity_view_display.node.sponsor.teaser.yml
- config/sync/field.field.node.sponsor.field_person.yml
- config/sync/field.storage.node.field_person.yml
- docroot/themes/custom/dckyiv/style/scss/components/_paragraph--sponsors.scss
- docroot/themes/custom/dckyiv/templates/content/node--sponsor--only-image.html.twig
> Add style for individual sponsors and enable stage for builds
> DCK-37: Add style for individual sponsor

- config/sync/core.entity_form_display.paragraph.timetable.default.yml
- config/sync/core.entity_form_display.paragraph.timetable_presentation.default.yml
- config/sync/core.entity_form_display.paragraph.timetable_slot.default.yml
- config/sync/core.entity_view_display.node.presentation.default.yml
- config/sync/core.entity_view_display.node.presentation.timetable_teaser.yml
- config/sync/core.entity_view_display.paragraph.timetable.default.yml
- config/sync/core.entity_view_display.paragraph.timetable_presentation.default.yml
- config/sync/core.entity_view_display.paragraph.timetable_slot.default.yml
- config/sync/core.entity_view_mode.node.timetable_teaser.yml
- config/sync/field.field.paragraph.timetable.field_timetable_slots.yml
- config/sync/field.field.paragraph.timetable.field_title.yml
- config/sync/field.field.paragraph.timetable_presentation.field_background.yml
- config/sync/field.field.paragraph.timetable_presentation.field_place.yml
- config/sync/field.field.paragraph.timetable_presentation.field_presentation_ref.yml
- config/sync/field.field.paragraph.timetable_slot.field_background.yml
- config/sync/field.field.paragraph.timetable_slot.field_content.yml
- config/sync/field.field.paragraph.timetable_slot.field_presentations.yml
- config/sync/field.field.paragraph.timetable_slot.field_time_slot.yml
- config/sync/field.storage.paragraph.field_background.yml
- config/sync/field.storage.paragraph.field_place.yml
- config/sync/field.storage.paragraph.field_presentation_ref.yml
- config/sync/field.storage.paragraph.field_presentations.yml
- config/sync/field.storage.paragraph.field_time_slot.yml
- config/sync/field.storage.paragraph.field_timetable_slots.yml
- config/sync/paragraphs.paragraphs_type.timetable.yml
- config/sync/paragraphs.paragraphs_type.timetable_presentation.yml
- config/sync/paragraphs.paragraphs_type.timetable_slot.yml
> **Prepared backend for timeslots paragraphs**
> DCK-83 Added Timeslots paragraphs.

- docroot/themes/custom/dckyiv/style/scss/components/_paragraph--timetable.scss
> DCK-104: Fix calendar button in the schedule

- .docksal/commands/rebuild
- docroot/themes/custom/dckyiv/package.json
> DCK-Gulp: Update package.json and add command to update npm

- docroot/themes/custom/dckyiv/style/scss/components/_node-presentation.scss
- docroot/themes/custom/dckyiv/templates/content/node--presentation--full.html.twig
> DCK-39: Add style for presentation page

- config/sync/core.entity_form_display.node.presentation.default.yml
- config/sync/core.entity_view_display.node.presentation.default.yml
> DCK-39: Add update for presentation config

- config/sync/core.entity_view_display.node.presentation.timetable_teaser.yml
- docroot/themes/custom/dckyiv/style/scss/components/_paragraph--timetable.scss
- docroot/themes/custom/dckyiv/templates/content/node--presentation--timetable-teaser.html.twig
> DCK-115: Add language and level of the presentation to the rozklad page.

- config/sync/field.field.paragraph.attendee.field_attendee_status.yml
- config/sync/views.view.attenders_overview.yml
- docroot/modules/custom/dckyiv_commerce/src/Controller/DckyivCommerceController.php
> Improved attendee overview report

- composer.json
- composer.lock
- config/sync/core.entity_form_display.node.landing_page.default.yml
- config/sync/core.entity_form_display.node.presentation.default.yml
- config/sync/core.entity_form_display.paragraph.presentations.default.yml
- config/sync/core.entity_form_display.paragraph.sponsor_wrapper.default.yml
- config/sync/core.entity_view_display.paragraph.attendee.mail.yml
- config/sync/field.field.paragraph.wrapper_webform.field_webform.yml
Notice: Indirect modification of overloaded element of Drupal\Core\Template\Attribute has no effect in Drupal\field_group\Element\HtmlElement::processHtmlElement() (line 58 of /var/www/docroot/modules/contrib/field_group/src/Element/HtmlElement.php) 
Issue was caused by outdated field groups configs for Landing page content type.
> Update field_group module and configs to fix notice

- config/sync/core.entity_form_display.media.remote_video.default.yml
- config/sync/core.entity_form_display.media.remote_video.media_library.yml
- config/sync/core.entity_form_display.node.presentation.default.yml
- config/sync/core.entity_form_display.paragraph.video.default.yml
- config/sync/core.entity_view_display.media.remote_video.media_library.yml
- config/sync/core.entity_view_display.node.presentation.default.yml
- config/sync/core.entity_view_display.node.presentation.timetable_teaser.yml
- config/sync/core.entity_view_display.paragraph.video.default.yml
- config/sync/core.extension.yml
- config/sync/editor.editor.full_html.yml
- config/sync/field.field.node.presentation.field_page_content.yml
- config/sync/field.field.paragraph.video.field_remote_video.yml
- config/sync/field.field.paragraph.video.field_title.yml
- config/sync/field.field.paragraph.video.field_wide_screen.yml
- config/sync/field.storage.media.field_media_oembed_video.yml
- config/sync/field.storage.paragraph.field_remote_video.yml
- config/sync/field.storage.paragraph.field_wide_screen.yml
- config/sync/filter.format.full_html.yml
- config/sync/image.style.video_embed_wysiwyg_preview.yml
- config/sync/paragraphs.paragraphs_type.video.yml
- docroot/themes/custom/dckyiv/style/scss/components/_paragraph--remote-video.scss
- docroot/themes/custom/dckyiv/templates/content/node--presentation--full.html.twig
- docroot/themes/custom/dckyiv/templates/paragraph/paragraph--video.html.twig
1. Added new Video paragraph type
2. Added paragraph field to the CT Presentation
> DCK-126: Add Video paragraph type

- composer.json
- config/sync/core.entity_form_display.paragraph.iframe.default.yml
- config/sync/core.entity_view_display.paragraph.iframe.default.yml
- config/sync/core.extension.yml
- config/sync/field.field.paragraph.iframe.field_iframe_source.yml
- config/sync/field.field.paragraph.iframe.field_wide_screen.yml
- config/sync/field.storage.paragraph.field_iframe_source.yml
- config/sync/field.storage.paragraph.field_wide_screen.yml
- config/sync/language.types.yml
- config/sync/paragraphs.paragraphs_type.iframe.yml
- config/sync/recaptcha.settings.yml
- docroot/themes/custom/dckyiv/style/scss/base/_drupal.scss
- docroot/themes/custom/dckyiv/style/scss/components/_paragraph--iframe.scss
- docroot/themes/custom/dckyiv/templates/paragraph/paragraph--iframe.html.twig
> DCK-127: Add iframe brick

- composer.json
- composer.lock
- config/sync/views.view.commerce_cart_form.yml
- config/sync/views.view.commerce_carts.yml
- docroot/themes/custom/dckyiv/style/scss/components/_paragraph--camp-products.scss
> DCK-70: Update style for block with tickets

- docroot/themes/custom/dckyiv/style/scss/base/_forms.scss
- docroot/themes/custom/dckyiv/style/scss/components/_node-presentation-form.scss
> DCK-181: Update styles for presentation page

- .gitignore
- docroot/themes/custom/dckyiv/dckyiv.libraries.yml
- docroot/themes/custom/dckyiv/js/swiper.js
- docroot/themes/custom/dckyiv/templates/paragraph/paragraph--camp-products.html.twig
- docroot/themes/custom/dckyiv/yarn.lock
The problem was in the modal window after a click on buy ticket.
It fixed to add the modal library to paragraph template.
> DCK-182: Fix modal window for buy ticket

- composer.json
- composer.lock
- config/sync/core.entity_form_display.paragraph.subscribe_block.default.yml
- config/sync/core.entity_view_display.paragraph.subscribe_block.default.yml
- config/sync/core.extension.yml
- config/sync/field.field.paragraph.subscribe_block.field_background_color.yml
- config/sync/field.field.paragraph.subscribe_block.field_background_image.yml
- config/sync/field.field.paragraph.subscribe_block.field_headline.yml
- config/sync/field.field.paragraph.subscribe_block.field_text.yml
- config/sync/field.field.paragraph.subscribe_block.field_text_color.yml
- config/sync/field.field.paragraph.subscribe_block.field_webform.yml
- config/sync/mailchimp.settings.yml
- config/sync/paragraphs.paragraphs_type.subscribe_block.yml
- config/sync/webform.webform.subscribe_form.yml
- docroot/themes/custom/dckyiv/style/scss/components/_paragraph--subscribe.scss
- docroot/themes/custom/dckyiv/templates/paragraph/paragraph--subscribe-block.html.twig
- docroot/themes/custom/dckyiv/yarn.lock
> DCK-183: Add Subscribe block

- composer.json
- composer.lock
- docroot/modules/custom/dckyiv_core/dckyiv_core.libraries.yml
> Add Composer 2.2+ support

- config/sync/mailsystem.settings.yml
- docroot/sites/default/settings.local.php
> Fix misconfiguration in mailsystem

- composer.json
- composer.lock
- config/sync/commerce_order.settings.yml
- config/sync/core.base_field_override.commerce_product.default.uid.yml
- config/sync/core.base_field_override.commerce_product_variation.default.uid.yml
- config/sync/core.entity_form_mode.profile.billing.yml
- config/sync/core.entity_view_display.commerce_order.default.default.yml
- config/sync/core.entity_view_display.commerce_order.drupal_camp_ticket.default.yml
- config/sync/views.view.commerce_promotion_coupons.yml
- config/sync/views.view.commerce_promotions.yml
> Update commerce module

- composer.json
- composer.lock
- config/sync/webform.settings.yml
- config/sync/webform.webform.contact.yml
- config/sync/webform.webform.subscribe_form.yml
> Update webform module

- docroot/modules/custom/dckyiv_user/dckyiv_user.module
> No need to check the html in the message, new module take care of that
